import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-background)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        surfaceDim: 'var(--color-surface-dim)',
        surfaceBright: 'var(--color-surface-bright)',
        surfaceContainerLowest: 'var(--color-surface-container-lowest)',
        surfaceContainerLow: 'var(--color-surface-container-low)',
        surfaceContainer: 'var(--color-surface-container)',
        surfaceContainerHigh: 'var(--color-surface-container-high)',
        surfaceContainerHighest: 'var(--color-surface-container-highest)',
        surfaceVariant: 'var(--color-surface-variant)',
        border: 'var(--color-outline-variant)',
        outline: 'var(--color-outline)',
        outlineVariant: 'var(--color-outline-variant)',
        text: 'var(--color-on-surface)',
        textMuted: 'var(--color-on-surface-variant)',
        textSubtle: 'var(--color-outline)',
        primary: 'var(--color-primary)',
        onPrimary: 'var(--color-on-primary)',
        primaryContainer: 'var(--color-primary-container)',
        onPrimaryContainer: 'var(--color-on-primary-container)',
        secondary: 'var(--color-secondary)',
        onSecondary: 'var(--color-on-secondary)',
        secondaryContainer: 'var(--color-secondary-container)',
        onSecondaryContainer: 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        onTertiary: 'var(--color-on-tertiary)',
        tertiaryContainer: 'var(--color-tertiary-container)',
        onTertiaryContainer: 'var(--color-on-tertiary-container)',
        inverseSurface: 'var(--color-inverse-surface)',
        inverseOnSurface: 'var(--color-inverse-on-surface)',
        inversePrimary: 'var(--color-inverse-primary)',
        danger: 'var(--color-error)',
        onDanger: 'var(--color-on-error)',
        dangerContainer: 'var(--color-error-container)',
        onDangerContainer: 'var(--color-on-error-container)',
        error: 'var(--color-error)',
        onError: 'var(--color-on-error)',
        errorContainer: 'var(--color-error-container)',
        onErrorContainer: 'var(--color-on-error-container)',
        success: 'var(--color-success)',
        onSuccess: 'var(--color-on-success)',
        successContainer: 'var(--color-success-container)',
        onSuccessContainer: 'var(--color-on-success-container)',
        warning: 'var(--color-warning)',
        onWarning: 'var(--color-on-warning)',
        warningContainer: 'var(--color-warning-container)',
        onWarningContainer: 'var(--color-on-warning-container)',
        accent: 'var(--color-primary)',
        accentStrong: 'var(--color-primary-container)',
        accentSoft: 'var(--color-secondary-container)',
        brand: {
          DEFAULT: 'var(--color-primary)',
          200: 'var(--color-primary-container)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        heading: ['var(--font-heading)'],
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
        pill: 'var(--radius-full)',
      },
      boxShadow: {
        e1: 'var(--elevation-1)',
        e2: 'var(--elevation-2)',
        e3: 'var(--elevation-3)',
        e4: 'var(--elevation-4)',
        e5: 'var(--elevation-5)',
      },
      spacing: {
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
      },
      size: {
        touchMd: 'var(--size-touch-md)',
        touchLg: 'var(--size-touch-lg)',
      },
    },
  },
}

export default config
